import Head from "next/head";
import Hero from "~/components/Hero/Hero";
import Skills from "~/components/Skills/Skills";
import WorkExperience from "~/components/WorkExperience/WorkExperience";
import ContactMe from "~/components/ContectMe/ContactMe";
import AboutMe from "~/components/AboutMe/AboutMe";

import "slick-carousel/slick/slick.css"
import "slick-carousel/slick/slick-theme.css"
import OtherExperience from "~/components/WorkExperience/OtherExperience";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ernst</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Hero/>
        <AboutMe/>
        <Skills/>
        <WorkExperience/>
        <OtherExperience/>
        <ContactMe/>
      </>
    </>
  )
}
